### PR TITLE
Update DesktopGL ref

### PR DESCRIPTION
**Pull request by cra0zy**
Sorry for taking so long

### CODE REVIEW

**Comment by craftworkgames** [comment]
What is this again?

**Comment by cra0zy** [comment]
#6

**Comment by craftworkgames** [comment]
I would really appreciate it if you gave a little more detail about what's actually changed. The last thing you said on #6 was

> I know what is causing the issue...

Okay. So you know what's causing the issue and you've submitted a compiled binary with a fix. But that kinda leaves me in the dark about what's actually changed? 

If someone asks me what this PR does I have no idea. If something doesn't work, or something breaks I have no idea what could have caused it. If you disappear of the face of the earth and I need to recompile the binary I wouldn't even know where to start.

Where did this binary come from? Is it a fork of the main MonoGame branch? What version is it? Does it incorporate lots of other changes? Is there a related issue on the MonoGame issues page? Have the changes been pulled into their repo?

I'm sorry for sounding harsh. I really do appreciate your help. I'd just like to be kept in the loop.

**Comment by cra0zy** [comment]
Just updates MonoGame Framework to the latest develop version.

Binary came from MG build server.

The bug was: https://github.com/mono/MonoGame/pull/4253/files

**Pull request merged**
