### PR TITLE
Master

### PR DESCRIPTION
**Pull request by ydyote**
Works in win8.1 VS2015 community

### CODE REVIEW

**Comment by craftworkgames** [comment]
If I remember correctly @cra0zy added the v3.5 DLL to allow Linux support. Unfortunately I don't have Linux box to test it on so it's hard to say what breaks.

Maybe we could have a `MonoGame.Framework.Windows.dll` and a `MonoGame.Framework.Linux.dll` in the 3rd party folder then update the respective [Launcer.Windows.csproj](https://github.com/craftworkgames/Samples.Extended/blob/master/Source/Launcher/Launcher.Windows.csproj#L42) and [Launcher.Linux.csproj](https://github.com/craftworkgames/Samples.Extended/blob/master/Source/Launcher/Launcher.Linux.csproj#L37) files to reference them?

**Comment by cra0zy** [comment]
> If I remember correctly @cra0zy added the v3.5 DLL to allow Linux support. Unfortunately I don't have Linux box to test it on so it's hard to say what breaks.

Yes, it's a version of 3.5

> Maybe we could have a MonoGame.Framework.Windows.dll and a MonoGame.Framework.Linux.dll in the 3rd party folder then update the respective Launcer.Windows.csproj and Launcher.Linux.csproj files to reference them?

WindowsGL and Linux assemblies are replaced with DesktopGL assemblies starting from 3.5 (one assembly that works on Windows, Linux and Mac). 

Why are you trying to downgrade? Also you would need 2 assemblies, one for Windows one for Linux, in order to do it.

**Comment by craftworkgames** [comment]
> Why are you trying to downgrade?

This PR is trying to fix issue #5 caused by breaking changes between 3.4 and 3.5

> The XNB format has changed between 3.4 and 3.5 and that is causing the issue.
> The list of targetPlatformIdentifiers in XNB files has changed between 3.4 and 3.5.
> In 3.4 'g' identifies WinGL
> In 3.5 'd' is used for this platform (and LinuxGL)
> https://github.com/mono/MonoGame/blob/master/MonoGame.Framework/Content/ContentManager.cs
> https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Content/ContentManager.cs
> To recapitulate: Do not use the 3.4 Content Pipeline Tool and MonoGame Framework 3.5 together :)

-
> Also you would need 2 assemblies, one for Windows one for Linux, in order to do it.

Yep, that's what I meant. Obviously, these problems will go away with v3.5 is officially released.

**Comment by cra0zy** [comment]
Having 2 dll files one for Windows, one for Linux sounds fine to me.

Side note MonoGame for Linux(and Mac) now supports .targets file with the development release, once 3.5 gets released we should be able to merge Windows and Linux projects into one.

**Comment by craftworkgames** [comment]
Does anyone have a Windows and Linux box that they can test on to resolve this issue?

**Comment by cra0zy** [comment]
I know what is causing the issue... will submit a fix to MonoGame and will update references here once it's merged.

**Pull request closed without merging**
